server:
  port: 80
  servlet:
    context-path: /movie

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_recommend?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 100
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/


#后台打印出sql语句
logging:
  level:
    cn.hstc.recommend.dao: debug

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: cn.hstc.recommend.*.entity
  #添加必要的配置
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false