server:
  port: 8088
  servlet:
    context-path: /movie

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_recommend?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

#后台打印出sql语句
logging:
  level:
    cn.hstc.recommend.dao: debug

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: cn.hstc.recommend.*.entity
  #添加必要的配置
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false